<?xml version="1.0" encoding="UTF-8" ?>
<testsuites>
  <testsuite errors="1" failures="0" hostname="DESKTOP-RKRLPOU" id="0" name="BaseControllerTests" package="racetrack" tests="1" time="4.252" timestamp="2017-06-29T06:55:37">
      <properties />

      <testcase classname="racetrack.BaseControllerTests" name="testSomething" time="3.61">
          <error message="Cannot add Controller class [class racetrack.BaseController]. It is not a Controller!" type="org.codehaus.groovy.grails.exceptions.GrailsConfigurationException">org.codehaus.groovy.grails.exceptions.GrailsConfigurationException: Cannot add Controller class [class racetrack.BaseController]. It is not a Controller!
	at grails.test.mixin.web.ControllerUnitTestMixin.mockController(ControllerUnitTestMixin.groovy:284)
</error>

      </testcase>

      <system-out><![CDATA[--Output from testSomething--
]]></system-out>

      <system-err><![CDATA[--Output from testSomething--
]]></system-err>

  </testsuite>
  <testsuite errors="0" failures="5" hostname="DESKTOP-RKRLPOU" id="1" name="RaceControllerTests" package="racetrack" tests="8" time="7.73" timestamp="2017-06-29T06:55:41">
      <properties />

      <testcase classname="racetrack.RaceControllerTests" name="testIndex" time="3.119" />

      <testcase classname="racetrack.RaceControllerTests" name="testList" time="2.397" />

      <testcase classname="racetrack.RaceControllerTests" name="testCreate" time="0.46" />

      <testcase classname="racetrack.RaceControllerTests" name="testSave" time="0.344">
          <failure message="Assertion failed: &#xa;&#xa;assert response.redirectedUrl == &apos;/race/show/1&apos;&#xa;       |        |             |&#xa;       |        null          false&#xa;       org.codehaus.groovy.grails.plugins.testing.GrailsMockHttpServletResponse@7bfea51e&#xa;" type="junit.framework.AssertionFailedError">junit.framework.AssertionFailedError: Assertion failed: 

assert response.redirectedUrl == &apos;/race/show/1&apos;
       |        |             |
       |        null          false
       org.codehaus.groovy.grails.plugins.testing.GrailsMockHttpServletResponse@7bfea51e

	at racetrack.RaceControllerTests.testSave(RaceControllerTests.groovy:48)
</failure>

      </testcase>

      <testcase classname="racetrack.RaceControllerTests" name="testShow" time="0.549">
          <failure message="Assertion failed: &#xa;&#xa;assert race.save() != null&#xa;       |    |      |&#xa;       |    null   false&#xa;       null : null, null&#xa;" type="junit.framework.AssertionFailedError">junit.framework.AssertionFailedError: Assertion failed: 

assert race.save() != null
       |    |      |
       |    null   false
       null : null, null

	at racetrack.RaceControllerTests.testShow(RaceControllerTests.groovy:62)
</failure>

      </testcase>

      <testcase classname="racetrack.RaceControllerTests" name="testEdit" time="0.334">
          <failure message="Assertion failed: &#xa;&#xa;assert race.save() != null&#xa;       |    |      |&#xa;       |    null   false&#xa;       null : null, null&#xa;" type="junit.framework.AssertionFailedError">junit.framework.AssertionFailedError: Assertion failed: 

assert race.save() != null
       |    |      |
       |    null   false
       null : null, null

	at racetrack.RaceControllerTests.testEdit(RaceControllerTests.groovy:80)
</failure>

      </testcase>

      <testcase classname="racetrack.RaceControllerTests" name="testUpdate" time="0.238">
          <failure message="Assertion failed: &#xa;&#xa;assert race.save() != null&#xa;       |    |      |&#xa;       |    null   false&#xa;       null : null, null&#xa;" type="junit.framework.AssertionFailedError">junit.framework.AssertionFailedError: Assertion failed: 

assert race.save() != null
       |    |      |
       |    null   false
       null : null, null

	at racetrack.RaceControllerTests.testUpdate(RaceControllerTests.groovy:100)
</failure>

      </testcase>

      <testcase classname="racetrack.RaceControllerTests" name="testDelete" time="0.137">
          <failure message="Assertion failed: &#xa;&#xa;assert race.save() != null&#xa;       |    |      |&#xa;       |    null   false&#xa;       null : null, null&#xa;" type="junit.framework.AssertionFailedError">junit.framework.AssertionFailedError: Assertion failed: 

assert race.save() != null
       |    |      |
       |    null   false
       null : null, null

	at racetrack.RaceControllerTests.testDelete(RaceControllerTests.groovy:144)
</failure>

      </testcase>

      <system-out><![CDATA[--Output from testIndex--
--Output from testList--
--Output from testCreate--
--Output from testSave--
--Output from testShow--
--Output from testEdit--
--Output from testUpdate--
--Output from testDelete--
]]></system-out>

      <system-err><![CDATA[--Output from testIndex--
--Output from testList--
--Output from testCreate--
--Output from testSave--
--Output from testShow--
--Output from testEdit--
--Output from testUpdate--
--Output from testDelete--
]]></system-err>

  </testsuite>
  <testsuite errors="0" failures="3" hostname="DESKTOP-RKRLPOU" id="2" name="RaceTests" package="racetrack" tests="4" time="1.199" timestamp="2017-06-29T06:55:49">
      <properties />

      <testcase classname="racetrack.RaceTests" name="testNameMaxConstraint" time="0.366">
          <failure message="junit.framework.AssertionFailedError" type="junit.framework.AssertionFailedError">junit.framework.AssertionFailedError: junit.framework.AssertionFailedError
	at racetrack.RaceTests.assertValidationError(RaceTests.groovy:68)
	at racetrack.RaceTests.testNameMaxConstraint(RaceTests.groovy:42)
</failure>

      </testcase>

      <testcase classname="racetrack.RaceTests" name="testSomething" time="0.098">
          <failure message="junit.framework.AssertionFailedError" type="junit.framework.AssertionFailedError">junit.framework.AssertionFailedError: junit.framework.AssertionFailedError
	at racetrack.RaceTests.testSomething(RaceTests.groovy:22)
</failure>

      </testcase>

      <testcase classname="racetrack.RaceTests" name="testStartDateTimeCustomConstraintWithPastValue" time="0.05" />

      <testcase classname="racetrack.RaceTests" name="testStartDateTimeCustomConstraintWithNullValue" time="0.086">
          <failure message="junit.framework.AssertionFailedError" type="junit.framework.AssertionFailedError">junit.framework.AssertionFailedError: junit.framework.AssertionFailedError
	at racetrack.RaceTests.assertValidationError(RaceTests.groovy:68)
	at racetrack.RaceTests.testStartDateTimeCustomConstraintWithNullValue(RaceTests.groovy:28)
</failure>

      </testcase>

      <system-out><![CDATA[--Output from testNameMaxConstraint--
--Output from testSomething--
--Output from testStartDateTimeCustomConstraintWithPastValue--
--Output from testStartDateTimeCustomConstraintWithNullValue--
]]></system-out>

      <system-err><![CDATA[--Output from testNameMaxConstraint--
--Output from testSomething--
--Output from testStartDateTimeCustomConstraintWithPastValue--
--Output from testStartDateTimeCustomConstraintWithNullValue--
]]></system-err>

  </testsuite>
  <testsuite errors="0" failures="1" hostname="DESKTOP-RKRLPOU" id="3" name="RaceTrackTagLibTests" package="racetrack" tests="1" time="1.568" timestamp="2017-06-29T06:55:50">
      <properties />

      <testcase classname="racetrack.RaceTrackTagLibTests" name="testSomething" time="1.018">
          <failure message="junit.framework.AssertionFailedError: Implement me" type="junit.framework.AssertionFailedError">junit.framework.AssertionFailedError: junit.framework.AssertionFailedError: Implement me
	at racetrack.RaceTrackTagLibTests.testSomething(RaceTrackTagLibTests.groovy:15)
</failure>

      </testcase>

      <system-out><![CDATA[--Output from testSomething--
]]></system-out>

      <system-err><![CDATA[--Output from testSomething--
]]></system-err>

  </testsuite>
  <testsuite errors="0" failures="5" hostname="DESKTOP-RKRLPOU" id="4" name="RegistrationControllerTests" package="racetrack" tests="8" time="3.123" timestamp="2017-06-29T06:55:52">
      <properties />

      <testcase classname="racetrack.RegistrationControllerTests" name="testIndex" time="1.144" />

      <testcase classname="racetrack.RegistrationControllerTests" name="testList" time="0.237" />

      <testcase classname="racetrack.RegistrationControllerTests" name="testCreate" time="0.216" />

      <testcase classname="racetrack.RegistrationControllerTests" name="testSave" time="0.168">
          <failure message="Assertion failed: &#xa;&#xa;assert response.redirectedUrl == &apos;/registration/show/1&apos;&#xa;       |        |             |&#xa;       |        null          false&#xa;       org.codehaus.groovy.grails.plugins.testing.GrailsMockHttpServletResponse@291d335e&#xa;" type="junit.framework.AssertionFailedError">junit.framework.AssertionFailedError: Assertion failed: 

assert response.redirectedUrl == &apos;/registration/show/1&apos;
       |        |             |
       |        null          false
       org.codehaus.groovy.grails.plugins.testing.GrailsMockHttpServletResponse@291d335e

	at racetrack.RegistrationControllerTests.testSave(RegistrationControllerTests.groovy:48)
</failure>

      </testcase>

      <testcase classname="racetrack.RegistrationControllerTests" name="testShow" time="0.18">
          <failure message="Assertion failed: &#xa;&#xa;assert registration.save() != null&#xa;       |            |      |&#xa;       null:null    null   false&#xa;" type="junit.framework.AssertionFailedError">junit.framework.AssertionFailedError: Assertion failed: 

assert registration.save() != null
       |            |      |
       null:null    null   false

	at racetrack.RegistrationControllerTests.testShow(RegistrationControllerTests.groovy:62)
</failure>

      </testcase>

      <testcase classname="racetrack.RegistrationControllerTests" name="testEdit" time="0.343">
          <failure message="Assertion failed: &#xa;&#xa;assert registration.save() != null&#xa;       |            |      |&#xa;       null:null    null   false&#xa;" type="junit.framework.AssertionFailedError">junit.framework.AssertionFailedError: Assertion failed: 

assert registration.save() != null
       |            |      |
       null:null    null   false

	at racetrack.RegistrationControllerTests.testEdit(RegistrationControllerTests.groovy:80)
</failure>

      </testcase>

      <testcase classname="racetrack.RegistrationControllerTests" name="testUpdate" time="0.304">
          <failure message="Assertion failed: &#xa;&#xa;assert registration.save() != null&#xa;       |            |      |&#xa;       null:null    null   false&#xa;" type="junit.framework.AssertionFailedError">junit.framework.AssertionFailedError: Assertion failed: 

assert registration.save() != null
       |            |      |
       null:null    null   false

	at racetrack.RegistrationControllerTests.testUpdate(RegistrationControllerTests.groovy:100)
</failure>

      </testcase>

      <testcase classname="racetrack.RegistrationControllerTests" name="testDelete" time="0.18">
          <failure message="Assertion failed: &#xa;&#xa;assert registration.save() != null&#xa;       |            |      |&#xa;       null:null    null   false&#xa;" type="junit.framework.AssertionFailedError">junit.framework.AssertionFailedError: Assertion failed: 

assert registration.save() != null
       |            |      |
       null:null    null   false

	at racetrack.RegistrationControllerTests.testDelete(RegistrationControllerTests.groovy:144)
</failure>

      </testcase>

      <system-out><![CDATA[--Output from testIndex--
--Output from testList--
--Output from testCreate--
--Output from testSave--
--Output from testShow--
--Output from testEdit--
--Output from testUpdate--
--Output from testDelete--
]]></system-out>

      <system-err><![CDATA[--Output from testIndex--
--Output from testList--
--Output from testCreate--
--Output from testSave--
--Output from testShow--
--Output from testEdit--
--Output from testUpdate--
--Output from testDelete--
]]></system-err>

  </testsuite>
  <testsuite errors="0" failures="1" hostname="DESKTOP-RKRLPOU" id="5" name="RegistrationTests" package="racetrack" tests="1" time="0.707" timestamp="2017-06-29T06:55:55">
      <properties />

      <testcase classname="racetrack.RegistrationTests" name="testSomething" time="0.296">
          <failure message="junit.framework.AssertionFailedError: Implement me" type="junit.framework.AssertionFailedError">junit.framework.AssertionFailedError: junit.framework.AssertionFailedError: Implement me
	at racetrack.RegistrationTests.testSomething(RegistrationTests.groovy:15)
</failure>

      </testcase>

      <system-out><![CDATA[--Output from testSomething--
]]></system-out>

      <system-err><![CDATA[--Output from testSomething--
]]></system-err>

  </testsuite>
  <testsuite errors="0" failures="5" hostname="DESKTOP-RKRLPOU" id="6" name="UserControllerTests" package="racetrack" tests="8" time="1.916" timestamp="2017-06-29T06:55:56">
      <properties />

      <testcase classname="racetrack.UserControllerTests" name="testIndex" time="0.707" />

      <testcase classname="racetrack.UserControllerTests" name="testList" time="0.113" />

      <testcase classname="racetrack.UserControllerTests" name="testCreate" time="0.128" />

      <testcase classname="racetrack.UserControllerTests" name="testSave" time="0.089">
          <failure message="Assertion failed: &#xa;&#xa;assert response.redirectedUrl == &apos;/user/show/1&apos;&#xa;       |        |             |&#xa;       |        null          false&#xa;       org.codehaus.groovy.grails.plugins.testing.GrailsMockHttpServletResponse@1ab6fd2b&#xa;" type="junit.framework.AssertionFailedError">junit.framework.AssertionFailedError: Assertion failed: 

assert response.redirectedUrl == &apos;/user/show/1&apos;
       |        |             |
       |        null          false
       org.codehaus.groovy.grails.plugins.testing.GrailsMockHttpServletResponse@1ab6fd2b

	at racetrack.UserControllerTests.testSave(UserControllerTests.groovy:48)
</failure>

      </testcase>

      <testcase classname="racetrack.UserControllerTests" name="testShow" time="0.11">
          <failure message="Assertion failed: &#xa;&#xa;assert user.save() != null&#xa;       |    |      |&#xa;       |    null   false&#xa;       racetrack.User : (unsaved)&#xa;" type="junit.framework.AssertionFailedError">junit.framework.AssertionFailedError: Assertion failed: 

assert user.save() != null
       |    |      |
       |    null   false
       racetrack.User : (unsaved)

	at racetrack.UserControllerTests.testShow(UserControllerTests.groovy:62)
</failure>

      </testcase>

      <testcase classname="racetrack.UserControllerTests" name="testEdit" time="0.143">
          <failure message="Assertion failed: &#xa;&#xa;assert user.save() != null&#xa;       |    |      |&#xa;       |    null   false&#xa;       racetrack.User : (unsaved)&#xa;" type="junit.framework.AssertionFailedError">junit.framework.AssertionFailedError: Assertion failed: 

assert user.save() != null
       |    |      |
       |    null   false
       racetrack.User : (unsaved)

	at racetrack.UserControllerTests.testEdit(UserControllerTests.groovy:80)
</failure>

      </testcase>

      <testcase classname="racetrack.UserControllerTests" name="testUpdate" time="0.186">
          <failure message="Assertion failed: &#xa;&#xa;assert user.save() != null&#xa;       |    |      |&#xa;       |    null   false&#xa;       racetrack.User : (unsaved)&#xa;" type="junit.framework.AssertionFailedError">junit.framework.AssertionFailedError: Assertion failed: 

assert user.save() != null
       |    |      |
       |    null   false
       racetrack.User : (unsaved)

	at racetrack.UserControllerTests.testUpdate(UserControllerTests.groovy:100)
</failure>

      </testcase>

      <testcase classname="racetrack.UserControllerTests" name="testDelete" time="0.106">
          <failure message="Assertion failed: &#xa;&#xa;assert user.save() != null&#xa;       |    |      |&#xa;       |    null   false&#xa;       racetrack.User : (unsaved)&#xa;" type="junit.framework.AssertionFailedError">junit.framework.AssertionFailedError: Assertion failed: 

assert user.save() != null
       |    |      |
       |    null   false
       racetrack.User : (unsaved)

	at racetrack.UserControllerTests.testDelete(UserControllerTests.groovy:144)
</failure>

      </testcase>

      <system-out><![CDATA[--Output from testIndex--
--Output from testList--
--Output from testCreate--
--Output from testSave--
--Output from testShow--
--Output from testEdit--
--Output from testUpdate--
--Output from testDelete--
]]></system-out>

      <system-err><![CDATA[--Output from testIndex--
--Output from testList--
--Output from testCreate--
--Output from testSave--
--Output from testShow--
--Output from testEdit--
--Output from testUpdate--
--Output from testDelete--
]]></system-err>

  </testsuite>
  <testsuite errors="0" failures="1" hostname="DESKTOP-RKRLPOU" id="7" name="UserTests" package="racetrack" tests="1" time="0.144" timestamp="2017-06-29T06:55:58">
      <properties />

      <testcase classname="racetrack.UserTests" name="testSomething" time="0.142">
          <failure message="junit.framework.AssertionFailedError: Implement me" type="junit.framework.AssertionFailedError">junit.framework.AssertionFailedError: junit.framework.AssertionFailedError: Implement me
	at racetrack.UserTests.testSomething(UserTests.groovy:15)
</failure>

      </testcase>

      <system-out><![CDATA[--Output from testSomething--
]]></system-out>

      <system-err><![CDATA[--Output from testSomething--
]]></system-err>

  </testsuite>
</testsuites>
